web/router.ex
defmodule Healthlocker.Router do
  use Healthlocker.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Healthlocker.Plugs.Auth, repo: Healthlocker.Repo
    plug :find_room
  end

  pipeline :logged_in do
    plug Healthlocker.Plugs.RequireLogin
    plug :find_room
  end

  pipeline :admin do
    plug Healthlocker.Plugs.RequireAdmin
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  # endpoints requiring an admin user
  scope "/", Healthlocker do
    pipe_through [:browser, :admin]

    resources "/posts", PostController, only: [:new, :create, :edit, :update]
  end
  
  # endpoints not requiring a logged in user
  scope "/", Healthlocker do
    pipe_through :browser

    get "/", PageController, :index
    resources "/feedback", FeedbackController, only: [:index, :create]
    resources "/login", LoginController, only: [:index, :create, :delete]
    resources "/users", UserController, only: [:index, :new, :create, :update] do
      get "/signup2", UserController, :signup2
      put "/create2", UserController, :create2
      get "/signup3", UserController, :signup3
      put "/create3", UserController, :create3
    end
    resources "/pages", PageController, only: [:index, :show]
    resources "/posts", PostController, only: [:show, :index]
    resources "/support", SupportController, only: [:index]
    resources "/tips", TipController, only: [:index]
    resources "/password", PasswordController, only: [:new, :create, :edit, :update]
    resources "/epjs-button", ButtonController, only: [:index]
    resources "/caseload", CaseloadController, only: [:index]
  end

  # endpoints requiring a logged in user
  scope "/", Healthlocker do
    pipe_through [:browser, :logged_in]

    resources "/posts", PostController, only: [:show, :index] do
      post "/likes", PostController, :likes
    end

    resources "/coping-strategy", CopingStrategyController
    resources "/goal", GoalController
    resources "/toolkit", ToolkitController, only: [:index]
    resources "/account", AccountController, only: [:index]
    put "/account/update", AccountController, :update
    put "/account/disconnect", AccountController, :disconnect
    get "/account/consent", AccountController, :consent
    put "/account/consent/update", AccountController, :update_consent
    get "/account/security/edit", AccountController, :edit_security
    put "/account/security/update", AccountController, :update_security
    get "/account/password/edit", AccountController, :edit_password
    put "/account/password/update", AccountController, :update_password
    get "/account/slam", AccountController, :slam
    put "/account/check-slam", AccountController, :check_slam
    resources "/components", ComponentController, only: [:index]
    resources "/messages", MessageController, only: [:index]
    resources "/sleep-tracker", SleepTrackerController, only: [:new, :create]
    resources "/care-plan", CarePlanController, only: [:index]

    scope "/care-team", CareTeam, as: :care_team do
      resources "/rooms", RoomController, only: [:show]
      resources "/contacts", ContactController, only: [:show], singleton: true
    end

    scope "/caseload", Caseload, as: :caseload do
      resources "/users", UserController, only: [:show, :index] do
        resources "/rooms", RoomController, only: [:show]
      end
    end

    resources "/slam", SlamController, only: [:new, :create]
    resources "/symptom", SymptomController, only: [:new, :create]
    resources "/symptom-tracker", SymptomTrackerController, only: [:new, :create]
    resources "/tracking-overview", TrackerController, only: [:index] do
      get "/prev-date", TrackerController, :prev_date
      get "/next-date", TrackerController, :next_date
    end
    resources "/diary", DiaryController, only: [:new, :create, :edit, :update]
  end

  scope "/", Healthlocker do
    get "/_version", GithubVersionController, :index # for deployment versioning
  end
end

web/views/layout_view.ex
defmodule Healthlocker.LayoutView do
  use Healthlocker.Web, :view
  alias Healthlocker.Repo

  def segment_snippet do
    if segment_write_key(), do: render(Healthlocker.LayoutView, "_segment.html")
  end

  def segment? do
    !!System.get_env("SEGMENT_WRITE_KEY")
  end

  defp segment_write_key do
    System.get_env("SEGMENT_WRITE_KEY")
  end

  def care_team?(user) do
    user = user |> Repo.preload(:caring)

    case user.caring do
      [] ->
        case user.role do
          "carer" -> true
          _ -> false
        end
      _ -> true
    end
  end

  def nav_bar_classes(list, "account-security") do
    case Enum.member?(list, "account") || Enum.member?(list, "security") do
      true -> "f3 white-80 db hover-white b"
      false -> "f3 white-80 db hover-white"
    end
  end

  def nav_bar_classes(list, string) do
    if string === "home" && list === [] do
      "f3 white-80 db hover-white b"
    else
      case Enum.member?(list, string) do
        true -> "f3 white-80 db hover-white b"
        false -> "f3 white-80 db hover-white"
      end
    end
  end
end

web/templates/layout/_segment.html.eex
<script type="text/javascript">
  (function(){

    // Create a queue, but don't obliterate an existing one!
    var analytics = window.analytics = window.analytics || [];

    // If the real analytics.js is already on the page return.
    if (analytics.initialize) return;

    // If the snippet was invoked already show an error.
    if (analytics.invoked) {
      if (window.console && console.error) {
        console.error('Segment snippet included twice.');
      }
      return;
    }

    // Invoked flag, to make sure the snippet
    // is never invoked twice.
    analytics.invoked = true;

    // A list of the methods in Analytics.js to stub.
    analytics.methods = [
      'trackSubmit',
      'trackClick',
      'trackLink',
      'trackForm',
      'pageview',
      'identify',
      'reset',
      'group',
      'track',
      'ready',
      'alias',
      'debug',
      'page',
      'once',
      'off',
      'on'
    ];

    // Define a factory to create stubs. These are placeholders
    // for methods in Analytics.js so that you never have to wait
    // for it to load to actually record data. The `method` is
    // stored as the first argument, so we can replay the data.
    analytics.factory = function(method){
      return function(){
        var args = Array.prototype.slice.call(arguments);
        args.unshift(method);
        analytics.push(args);
        return analytics;
      };
    };

    // For each of our methods, generate a queueing stub.
    for (var i = 0; i < analytics.methods.length; i++) {
      var key = analytics.methods[i];
      analytics[key] = analytics.factory(key);
    }

    // Define a method to load Analytics.js from our CDN,
    // and that will be sure to only ever load it once.
    analytics.load = function(key){
      // Create an async script element based on your key.
      var script = document.createElement('script');
      script.type = 'text/javascript';
      script.async = true;
      script.src = ('https:' === document.location.protocol
        ? 'https://' : 'http://')
        + 'cdn.segment.com/analytics.js/v1/'
        + key + '/analytics.min.js';

      // Insert our script next to the first script element.
      var first = document.getElementsByTagName('script')[0];
      first.parentNode.insertBefore(script, first);
    };

    // Add a version to keep track of what's in the wild.
    analytics.SNIPPET_VERSION = '4.0.0';

    // Load Analytics.js with your key, which will automatically
    // load the tools you've enabled for your account. Boosh!
    analytics.load("<%= segment_write_key() %>");

    // Make the first page call to load the integrations. If
    // you'd like to manually name or tag the page, edit or
    // move this call however you'd like.
    analytics.page();
  })();

</script>

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Healthlocker</title>
    <link rel="stylesheet" href="https://unpkg.com/tachyons@4.6.1/css/tachyons.min.css"/>
    <link rel=stylesheet href="https://s3-us-west-2.amazonaws.com/colors-css/2.2.0/colors.min.css">
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
    <link href="https://fonts.googleapis.com/css?family=Didact+Gothic" rel="stylesheet">
    <link rel="icon" type="image/png" href="/images/favicon-hl-32x32.png">
    <link rel=”apple-touch-icon” href=”/images/apple-touch-icon.png”/>
    <link rel=”apple-touch-icon-precomposed” href=”/images/apple-touch-icon.png”/>

    <%= segment_snippet() %>
  </head>
  <body class="w-100 bg-white">

    <%= if !@current_user && @conn.request_path == "/" do %>
      <div class="pa1 w-100 w-70-m w-70-l">
        <%= img_tag("/images/nhs-logo.png", class: "w-60 w-40-m w-40-l mw7") %>
      </div>
    <% end %>

    <div class="hl-bg-pink pa1">
      <div class="pa1">
        <p class="di b white">Healthlocker is in progress -</p>
        <small>
          <%= link "share feedback and suggestions",
          to: feedback_path(@conn, :index), class: "white" %>
        </small>
      </div>
    </div>

    <div class="container">
      <header id="header" class="hl-bg-aqua w-100 ph3 pv3 pv4-ns ph4-m ph4-l tc">
        <nav class="f2 fw3 relative">
          <div class="tc">
            <a href="/"><%= img_tag("/images/logo.png", class: "w-60 w-50-m mw5") %></a>
          </div>
          <i id="open-nav" class="fa fa-bars dim white dib fl pointer absolute top-0 left-0"></i>
          <div class="fr dn dib-m dib-l absolute top-0 right-0">
            <%= cond do %>
              <%= !@current_user -> %>
                <%= link_primary "Log in", to: login_path(@conn, :index) %>
              <% @current_user && @current_user.role != "clinician" -> %>
                <%= link_primary "Log out", to: login_path(@conn, :delete, @current_user),
                    method: "delete"%>
              <% @current_user && @current_user.role == "clinician" -> %>
                <%= link_primary "Caseload", to: caseload_path(@conn, :index) %>
              <% true -> %>
                <%= link_primary "Log in", to: login_path(@conn, :index) %>
            <% end %>
          </div>
        </nav>
      </header>

      <nav class="sidenav vh-100 fixed z-1 top-0 left-0 hl-bg-dark-blue overflow-x-hidden tc measure-narrow-l br-l b--white" id="my-sidenav">
        <%= img_tag("/images/x_icon.svg", id: "close-nav", class: "w2 mt5 pointer") %>
        <%= if @current_user do %>
          <%= link "Goals and tracking",  class: "pb3 pt4 pt5-l " <> nav_bar_classes(@conn.path_info, "toolkit"),
              to: toolkit_path(@conn, :index) %>
          <%= if care_team?(@current_user) or @current_user.slam_id do %>
            <%= link "Care team", class: "pa3 " <> nav_bar_classes(@conn.path_info, "care-team"),
                to: care_team_room_path(@conn, :show, @room) %>
          <% end %>
        <% else %>
          <%= link "Home", to: page_path(@conn, :index), class: "pb3 pt4 pt5-l " <> nav_bar_classes(@conn.path_info, "home") %>
          <%= link "About", to: page_path(@conn, :show, "about"), class: "pa3 " <> nav_bar_classes(@conn.path_info, "about") %>
        <% end %>
        <%= link "Tips", to: tip_path(@conn, :index), class: "pa3 " <> nav_bar_classes(@conn.path_info, "tips") %>
        <%= link "Stories", to: post_path(@conn, :index), class: "pa3 " <> nav_bar_classes(@conn.path_info, "posts") %>
        <%= link "Get support", to: support_path(@conn, :index), class: "mv3 mh5 mh6-m hl-bg-pink pv2 f3 white-80 db hover-white" %>
        <%= if @current_user do %>
          <%= link "Account", to: account_path(@conn, :index),
                   class: "pa3 " <> nav_bar_classes(@conn.path_info, "account-security") %>

          <%= link "Log out", class: "pa3 mb6 mb0-m mb0-l f3 white-80 db hover-white",
                             to: login_path(@conn, :delete, @current_user),
                             method: "delete" %>
        <% else %>
          <%= link "Sign up", class: "pa3 " <> nav_bar_classes(@conn.path_info, "new"),
              to: user_path(@conn, :new) %>
          <%= link "Log in", class: "pa3 mb6 mb0-m mb0-l " <> nav_bar_classes(@conn.path_info, "login"),
              to: login_path(@conn, :index) %>
        <% end %>
      </nav>

      <main id="body">
        <section class="h-100 ph3 ph5-ns pb3 bt b--black-10 bg-white">
          <section class="mw7 center">
            <%
              info = get_flash(@conn, :info)
              error = get_flash(@conn, :error)
            %>
            <%= if info do %>
              <div class="ba bw2 br3 b--hl-yellow hl-bg-success center tc pv2 pv3-l mh4-l mt4" role="alert"><%= get_flash(@conn, :info) %></div>
            <% end %>
            <%= if error do %>
              <div class="ba bw2 br3 b--hl-pink hl-bg-error center tc pv2 pv3-l mh4-l mt4" role="alert"><%= get_flash(@conn, :error) %></div>
            <% end %>
            <%= render @view_module, @view_template, assigns %>
          </section>
        </section>
      </main>
      <footer id="footer" class="db tc mt4 w-100">
        <div class="hl-bg-dark-blue w-100 h0-6"></div>
        <div class="w-100 center relative">
          <%= img_tag("/images/nhs_lozenge.png", class: "w-10-ns w-20 mw4 absolute-ns right-2-ns pa3 db ml-auto") %>
          <%= link "About", to: page_path(@conn, :show, "about"), class: "f6 link dim hl-dark-blue dib mr3 mr4-ns pt3-ns pb3" %>
          <%= link "Terms of Service", to: page_path(@conn, :show, "terms"), class: "f6 link dim hl-dark-blue dib mr3 mr4-ns pt3-ns pb3" %>
          <%= link "Privacy Statement", to: page_path(@conn, :show, "privacy"), class: "f6 link dim hl-dark-blue dib pt3-ns pb3" %>
        </div>
      </footer>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.js"></script>
    <script>window.userToken = "<%= assigns[:user_token] %>"</script>
    <script src="https://use.fontawesome.com/6a9dd6f59e.js"></script>
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
    <%= if @current_user && segment?() do %>
      <script type="text/javascript">
        require("web/static/js/segment").Segment.identify("<%= @current_user.id %>", "<%= @current_user.first_name %> <%= @current_user.last_name %>", "<%= @current_user.email %>")
      </script>
    <% end %>
  </body>
</html>