web/router.ex
defmodule Healthlocker.Router do
  use Healthlocker.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Healthlocker.Plugs.Auth, repo: Healthlocker.Repo
    plug :find_room
  end

  pipeline :logged_in do
    plug Healthlocker.Plugs.RequireLogin
    plug :find_room
  end

  pipeline :admin do
    plug Healthlocker.Plugs.RequireAdmin
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  # endpoints requiring an admin user
  scope "/", Healthlocker do
    pipe_through [:browser, :admin]

    resources "/posts", PostController, only: [:new, :create, :edit, :update]
  end
  
  # endpoints not requiring a logged in user
  scope "/", Healthlocker do
    pipe_through :browser

    get "/", PageController, :index
    resources "/feedback", FeedbackController, only: [:index, :create]
    resources "/login", LoginController, only: [:index, :create, :delete]
    resources "/users", UserController, only: [:index, :new, :create, :update] do
      get "/signup2", UserController, :signup2
      put "/create2", UserController, :create2
      get "/signup3", UserController, :signup3
      put "/create3", UserController, :create3
    end
    resources "/pages", PageController, only: [:index, :show]
    resources "/posts", PostController, only: [:show, :index]
    resources "/support", SupportController, only: [:index]
    resources "/tips", TipController, only: [:index]
    resources "/password", PasswordController, only: [:new, :create, :edit, :update]
    resources "/epjs-button", ButtonController, only: [:index]
    resources "/caseload", CaseloadController, only: [:index]
  end

  # endpoints requiring a logged in user
  scope "/", Healthlocker do
    pipe_through [:browser, :logged_in]

    resources "/posts", PostController, only: [:show, :index] do
      post "/likes", PostController, :likes
    end

    resources "/coping-strategy", CopingStrategyController
    resources "/goal", GoalController
    resources "/toolkit", ToolkitController, only: [:index]
    resources "/account", AccountController, only: [:index]
    put "/account/update", AccountController, :update
    put "/account/disconnect", AccountController, :disconnect
    get "/account/consent", AccountController, :consent
    put "/account/consent/update", AccountController, :update_consent
    get "/account/security/edit", AccountController, :edit_security
    put "/account/security/update", AccountController, :update_security
    get "/account/password/edit", AccountController, :edit_password
    put "/account/password/update", AccountController, :update_password
    get "/account/slam", AccountController, :slam
    put "/account/check-slam", AccountController, :check_slam
    resources "/components", ComponentController, only: [:index]
    resources "/messages", MessageController, only: [:index]
    resources "/sleep-tracker", SleepTrackerController, only: [:new, :create]
    resources "/care-plan", CarePlanController, only: [:index]

    scope "/care-team", CareTeam, as: :care_team do
      resources "/rooms", RoomController, only: [:show]
      resources "/contacts", ContactController, only: [:show], singleton: true
    end

    scope "/caseload", Caseload, as: :caseload do
      resources "/users", UserController, only: [:show, :index] do
        resources "/rooms", RoomController, only: [:show]
      end
    end

    resources "/slam", SlamController, only: [:new, :create]
    resources "/symptom", SymptomController, only: [:new, :create]
    resources "/symptom-tracker", SymptomTrackerController, only: [:new, :create]
    resources "/tracking-overview", TrackerController, only: [:index] do
      get "/prev-date", TrackerController, :prev_date
      get "/next-date", TrackerController, :next_date
    end
    resources "/diary", DiaryController, only: [:new, :create, :edit, :update]
  end

  scope "/", Healthlocker do
    get "/_version", GithubVersionController, :index # for deployment versioning
  end
end

web/models/goal.ex
defmodule Healthlocker.Goal do
  use Healthlocker.Web, :model

  schema "goals" do
    field :content, :string
    field :completed, :boolean
    field :notes, :string
    field :important, :boolean
    field :achieved_at, :date
    has_many :steps, Healthlocker.Step, on_delete: :delete_all,
                                        on_replace: :delete
    belongs_to :user, Healthlocker.User

    timestamps()
  end

  def changeset(struct, params \\ :invalid) do
    struct
    |> cast(params, [:content, :important, :completed, :notes])
    |> cast_assoc(:steps)
    |> validate_required(:content)
  end

  def set_achieved_at(changeset) do
    if get_change(changeset, :completed) do
      put_change(changeset, :achieved_at, Date.utc_today())
    else
      changeset
    end
  end

  def get_goals(query, user_id) do
    from g in query,
    where: like(g.content, "%#Goal") and g.user_id == ^user_id,
    order_by: [desc: g.updated_at],
    preload: [:steps]
  end

  def get_important_goals(query, user_id) do
    from g in query,
    where: like(g.content, "%#Goal") and g.user_id == ^user_id and g.important,
    order_by: [desc: g.updated_at],
    preload: [:steps]
  end

  def get_unimportant_goals(query, user_id) do
    from g in query,
    where: g.user_id == ^user_id and not g.important,
    order_by: [desc: g.updated_at],
    preload: [:steps]
  end

  def get_completed_goals(query, user_id) do
    from g in query,
    where: like(g.content, "%#Goal") and g.user_id == ^user_id and g.completed,
    order_by: [desc: g.updated_at],
    preload: [:steps]
  end

  def get_goal_by_user(query, id, user_id) do
    steps_query = from s in Healthlocker.Step, order_by: s.inserted_at
    from g in query,
    where: g.id == ^id and g.user_id == ^user_id,
    preload: [steps: ^steps_query]
  end
end

web/controllers/goal_controller.ex
defmodule Healthlocker.GoalController do
  use Healthlocker.Web, :controller
  alias Healthlocker.{Goal, Step}

  def index(conn, _params) do
    user_id = conn.assigns.current_user.id
    important_goals = Goal
                     |> Goal.get_important_goals(user_id)
                     |> Repo.all
    unimportant_goals = Goal
                     |> Goal.get_unimportant_goals(user_id)
                     |> Repo.all
    all_goals = Enum.concat(important_goals, unimportant_goals)

    incomplete_goals = all_goals
                      |> Enum.filter(fn goal ->
                        !goal.completed
                      end)
                      |> incomplete_goals_with_sorted_steps
    completed = Goal
              |> Goal.get_completed_goals(user_id)
              |> Repo.all

    if Kernel.length(all_goals) == 0 && Kernel.length(completed) do
      conn
      |> redirect(to: goal_path(conn, :new))
    else
      conn
      |> render("index.html", goals: incomplete_goals, complete_goals: completed)
    end
  end

  def new(conn, _params) do
    # Build up a collection of 5 associated steps.
    changeset = Goal.changeset(%Goal{
      steps: Enum.map(1..5, fn _ -> Step.changeset(%Step{}) end)
    })
    conn
    |> render("new.html", changeset: changeset)
  end

  def show(conn, %{"id" => id}) do
    user_id = conn.assigns.current_user.id
    goal = Goal
          |> Goal.get_goal_by_user(id, user_id)
          |> Repo.one!
    conn
    |> render("show.html", goal: goal)
  end

  def create(conn, %{"goal" => goal_params}) do
    content = get_content(goal_params)
    user_id = get_session(conn, :user_id)
    changeset = Goal.changeset(%Goal{}, content)
              |> Ecto.Changeset.put_change(:user_id, user_id)

    case Repo.insert(changeset) do
      {:ok, goal} ->
        conn |> track_created(goal)

        conn
        |> put_flash(:info, "Goal added!")
        |> redirect(to: goal_path(conn, :index))
      {:error, changeset} ->
        conn
        |> render("new.html", changeset: changeset)
    end
  end

  def edit(conn, %{"id" => id}) do
    user_id = conn.assigns.current_user.id
    goal = Goal
          |> Goal.get_goal_by_user(id, user_id)
          |> Repo.one
          |> Map.update!(:content, &(String.trim_trailing(&1, " #Goal")))
    changeset = Goal.changeset(goal)
    conn
    |> render("edit.html", goal: goal, changeset: changeset)
  end

  def update(conn, %{"id" => id, "goal" => goal_params}) do
    goal = Goal
      |> Repo.get!(id)
      |> Repo.preload(:steps)
    content = get_content(goal_params)
    changeset = Goal.changeset(goal, content)
              |> Goal.set_achieved_at()

    case Repo.update(changeset) do
      {:ok, _goal} ->
        conn
        |> put_flash(:info, "Goal updated successfully.")
        |> redirect(to: goal_path(conn, :index))
      {:error, changeset} ->
        conn
        |> render("edit.html", goal: goal, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    user_id = conn.assigns.current_user.id
    goal = Goal
          |> Goal.get_goal_by_user(id, user_id)
          |> Repo.one

    Repo.delete!(goal)

    conn
    |> put_flash(:info, "Goal deleted successfully.")
    |> redirect(to: goal_path(conn, :index))
  end

  def get_content(params) do
    if Map.has_key?(params, "content") && params["content"] != "" do
      Map.update(params, "content", params["content"], &(&1 <> " #Goal"))
    else
      params
    end
  end

  defp track_created(conn, %Goal{} = goal) do
    Healthlocker.Analytics.track(conn.assigns.current_user, :create, goal)
  end

  def incomplete_goals_with_sorted_steps(goals) do
    goals
    |> Enum.map(fn goal ->
      Map.update!(goal, :steps, fn steps -> sort_steps(steps) end)
    end)
  end

  def sort_steps(list) do
    sorted_list = Enum.sort(list, &(&1.id < &2.id))
    incomplete_steps = Enum.filter(sorted_list, &(&1.complete != true))
    complete_steps = Enum.filter(sorted_list, &(&1.complete == true))
    Enum.concat(incomplete_steps, complete_steps)
  end
end

web/views/goal_view.ex
defmodule Healthlocker.GoalView do
  use Healthlocker.Web, :view
  import Healthlocker.CopingStrategyView , only: [format_output: 2]
end

web/templates/goal/edit.html.eex
<h3 class="tc pv2 mh3 hl-dark-blue">Edit Goal</h3>

<section class="ma3 ma4-m ma4-l center">
  <p class="tl b">What do you want to achieve?</p>
  <p class="tl b">You may want to ensure your goal is SMART.</p>
  <p>
    <strong>Specific</strong>, be very clear about what you want to achieve.<br>
    <strong>Measurable</strong>, how will you know when you have achieved your goal? <br>
    <strong>Achievable</strong>, avoid setting yourself a challenge that is too big. <br>
    <strong>Resourced</strong>, do you have everything you need to achieve your goal?<br>
    <strong>Time limited</strong>, set a reasonable time frame to reach your goal.<br>
  </p>
  <p class="tl">Describe a personal goal.</p>
  <%= form_for @changeset, goal_path(@conn, :update, @goal), fn f -> %>
    <div class=" mb3 pb3 bb b--hl-grey bw2">
      <%= textarea f, :content, placeholder: "Content", class: "h4 db border-box hover-black w-100 ba b--black-20 pa2 br2 mb2 default-font" %>
    </div>
    <p class="b pt2 mb0">Steps to take:</p>
    <p class="mt1">List the things you could do to achieve this goal.</p>
    <p>Come back and tick each step off as you complete them.</p>
    <%= inputs_for f, :steps, fn s -> %>
      <div class="mb3">
        <%= checkbox s, :complete, class: "checkbox" %>
        <%= text_input s, :details, class: "ph3 input-reset bn hl-bg-grey w-90 " <>
          Healthlocker.ComponentView.highlight_errors(@changeset, :details) %>
      </div>
    <% end %>
    <div class=" mb3 pb3 bb b--hl-grey bw2"></div>
      <div class="relative mt4">
        <span class="b">Star as important</span>

        <%= checkbox f, :important, class: "o-0 checkbox star" %>
          <%= label f, :important, class: "star pointer" do %>
        <% end %>
        <p class="i">Important goals will be at the top of the list.</p>
      </div>
    <div class=" mb3 pb3 bb b--hl-grey bw2"> </div>
    <div class="relative mt4">
      <span class="b">Mark as achieved</span>
      <%= checkbox f, :completed, class: "dn checkbox complete" %>
          <%= label f, :completed, class: "complete pointer" do %>
      <% end %>
    </div>

    <div id="notes" class="mt4 dn">
      <%= label f, "Reflective notes:", class: "f5 b db mb2" %>
      <p>
        What went well? What problems did you have, how did you overcome
        them? How do you feel now?
      </p>
      <%= textarea f, :notes, class: "h4 db border-box hover-black w-100 ba b--black-20 pa2 br2 mb2 default-font" %>
    </div>

    <div class="tr mt3">
      <%= submit_primary "Save" %>
    </div>
  <% end %>
  <div class="tr mt4">
    <input type="checkbox" id="delete_goal" class="dn">
    <label for="delete_goal" class="link hl-aqua underline">Delete goal</label>
    <div class="delete-goal-div w5-plus h4 bg-white ba br3 absolute top-50-ns top-70 left-50 ml--8 dn">
      <div class="tc">
        <p class="tc pl2 pr2">Are you sure you want to delete this goal?</p>
        <%= link("Delete goal",
          to: goal_path(@conn, :delete, @goal),
          method: "delete",
          class: "f5 link dib ph3 pv2 br-pill hl-dark-blue pointer hl-shadow-hover
                  hl-bg-grey default-font")
        %>
        <input type="checkbox" class="dn">
        <label for="delete_goal" class="f5 link dib ph3 pv2 br-pill hl-dark-blue
                                        pointer hl-shadow-hover hl-bg-yellow
                                        default-font ml2">
                                        Cancel
        </label>
      </div>
    </div>
  </div>
</section>

web/templates/goal/form.html.eex
<section class="ma3 ma4-m ma4-l center">

 <p class="tl b">What do you want to achieve?</p>
 <p class="tl b">You may want to ensure your goal is SMART.</p>
   <p>  
     <strong>Specific</strong>, be very clear about what you want to achieve.<br>
     <strong>Measurable</strong>, how will you know when you have achieved your goal? <br>
      <strong>Achievable</strong>, avoid setting yourself a challenge that is too big. <br>
      <strong>Resourced</strong>, do you have everything you need to achieve your goal?<br>
      <strong>Time limited</strong>, set a reasonable time frame to reach your goal.<br> </p>
<p class="tl">Describe a personal goal.</p>
  
  <%= form_for @changeset, @action, fn f -> %>
      <div class=" mb3 pb3 bb b--hl-grey bw2">
        <%= textarea f, :content, placeholder: "Content", class: "db border-box hover-black w-100 ba b--black-20 pa2 br2 mb2 default-font" %>
      </div>
      <p class="b pt2 mb0">Steps to take:</p>
      <p class="mt1">List the things you could do to achieve this goal.</p>
        <p>Come back and tick each step off as you complete them.</p>
      <%= inputs_for f, :steps, fn s -> %>
        <div class="mb3">
          <%= checkbox s, :complete, class: "checkbox" %>
          <%= text_input s, :details, class: "ph3 input-reset bn hl-bg-grey w-90 " <>
            Healthlocker.ComponentView.highlight_errors(@changeset, :details) %>
        </div>
      <% end %>
 <div class=" mb3 pb3 bb b--hl-grey bw2"></div>
      <div class="relative mt4">
        Star as important

        <%= checkbox f, :important, class: "o-0 checkbox star" %>
          <%= label f, :important, class: "star pointer" do %>
        <% end %>
        <p class="i">Important goals will be at the top of the list.</p>
      </div>
  <div class=" mb3 pb3 bb b--hl-grey bw2"></div>
      <div class="tr">
        <%= submit_primary "Save" %>
      </div>
  <% end %>

</section>

web/templates/goal/index.html.eex
<div class="ma3 ma4-m ma4-l">
  <%= h2_header "My goals" %>

  <div class="db tr">
    <%= link_primary "Add new", to: goal_path(@conn, :new) %>
  </div>

  <%= for goal <- @goals do %>
    <%= link to: goal_path(@conn, :edit, goal), class: "link w-100" do %>
      <section class="bb bw2 b--black-10 dib w-100 word-wrap">
        <div class="w-90 dib fl">
          <h4 class="ma2 ph3-m ph4-l f5 lh-copy hl-dark-blue di w-100">
            <p><%= format_output(goal.content, " #Goal") %></p>
              <%= for step <- goal.steps do %>
                <%= if is_bitstring(step.details) do %>
                  <div>
                    <%= if step.complete do %>
                      <div class="db">
                        <div class="w1-15 dib pt1 v-mid">
                          <%= img_tag("/images/checked_box_grey.png", alt: "Checked box") %>
                        </div>
                        <p class="dib ml2 v-mid fw1"><%= step.details %></p>
                      </div>
                    <% else %>
                      <div class="db">
                        <div class="w1-15 dib pt1 v-mid">
                          <%= img_tag("/images/unchecked_box_grey.png", alt: "Unchecked box") %>
                        </div>
                        <p class="dib ml2 v-mid fw1"><%= step.details %></p>
                      </div>
                    <% end %>
                  </div>
                <% end %>
              <% end %>
          </h4>
        </div>
        <%= if goal.important do %>
          <div class="w-10 dib fr">
            <%= img_tag("/images/star_selected.svg",
                class: "w2 fr relative s-top") %>
          </div>
        <% end %>
      </section>
    <% end %>
  <% end %>

  <h3 class="mt5 mb3">Achieved goals</h3>
  <%= for goal <- @complete_goals do %>
    <%= link to: goal_path(@conn, :edit, goal), class: "link w-100" do %>
      <section class="ba bw2 b--black-10 dib pv3 w-100 mv2 relative">
        <%= img_tag("/images/Goal_Complete.png", class: "absolute w2 left--1-1 bottom-1-6") %>
          <div class="ma2 b hl-dark-blue w-80 w-90-m w-90-l center">
            <p><%= format_output(goal.content, " #Goal") %></p>
          </div>
          <p class="i hl-dark-blue ma2 w-80 w-90-m w-90-l center">Achieved:
            <%= Healthlocker.ComponentView.pretty_date(goal.achieved_at) %>
          </p>
      </section>
    <% end %>
  <% end %>
  <%= if @current_user.slam_id do %>
    <p class="hl-pink">Your Care team will also be able to see your Goals.</p>
  <% end %>
</div>

web/templates/goal/new.html.eex
<h3 class="tc pv2 mh3 hl-dark-blue">Add new</h3>

<%= render "form.html", changeset: @changeset,
                        action: goal_path(@conn, :create) %>

web/templates/goal/show.html.eex
<div class="ma3 ma4-m ma4-l">
  <h2 class="tc">View Goal</h2>
  <div class="tr">
    <%= link_to "Edit", to: goal_path(@conn, :edit, @goal) %>
  </div>

  <div class="hl-bg-grey pv1 ph3 mt2 word-wrap">
    <span class="b"><%= format_output(@goal.content, " #Goal") %></span>

    <%= for step <- @goal.steps do %>
      <%= if is_bitstring(step.details) do %>
        <div class="w-100 flex items-center mb1">
          <div class="w2 b--hl-yellow hl-bg-white ba br2 pa1 min-checkbox-height">
            <%= if step.complete do %>
              <%= img_tag("/images/tick.svg", class: "w-100 dib fl") %>
            <% end %>
          </div>
          <p class="ml2"><%= step.details %></p>
        </div>
      <% end %>
    <% end %>
  </div>

  <p class="mv3 f6 i">
    Created <%= Healthlocker.ComponentView.pretty_date(@goal.inserted_at) %>
  </p>

  <div class="tr mt3">
    <%= link_to "Back to Goals and tracking", to: toolkit_path(@conn, :index) %>
  </div>
</div>